# Generated by Django 4.1.5 on 2023-01-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logindash', '0002_bitcoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Contact us from telegram @maeybeyes', max_length=100)),
                ('wallet_address', models.TextField(default='Contact us from telegram @maeybeyes')),
                ('qrcode', models.FileField(upload_to='crypto/')),
                ('note', models.TextField(default='Contact us from telegram @maeybeyes')),
            ],
        ),
        migrations.DeleteModel(
            name='Bitcoin',
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.DeleteModel(
            name='Updates',
        ),
    ]
