# Generated by Django 4.1.5 on 2023-01-13 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logindash', '0004_notes_remove_cryptocurrency_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='qrcode',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(default='Contact us from telegram @nitrosupport24h', max_length=100),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='wallet_address',
            field=models.TextField(default='Contact us from telegram @nitrosupport24h'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='note',
            field=models.TextField(default='Contact us from telegram @nitrosupport24h'),
        ),
    ]
