# Generated by Django 4.1.5 on 2023-01-20 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logindash', '0005_remove_cryptocurrency_qrcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_body', models.CharField(default='After paid for service sent it from telegram', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.CharField(default='Thanks for your registration', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.CharField(default='Not any News yet', max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='Not service available yet', max_length=50)),
                ('service_price', models.CharField(default='-', max_length=50)),
                ('options', models.TextField(default='Not service available yet')),
            ],
        ),
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatee', models.CharField(default='Not any Updates yet', max_length=240)),
            ],
        ),
    ]
